---
argument_specs:
  main:
    short_description: Runs pre-upgrade test suite and takes an operational snapshot.
    description:
      - >-
        Runs the pre-upgrade ('readiness') tests and takes a snapshot of the operational state of the target 
        firewall.
    options:
      left_snapshot:
        type: "str"
        required: true
        description: "The first snapshot to compare, usually this snapshot is the one taken before any upgrades"
      right_snapshot:
        type: "str"
        required: true
        description: "The second snapshot to compare, usually this snapshot is the one taken after any upgrades or changes"
      report_output_file:
        type: "str"
        required: false
        description: "The name of the report to save. Defaults to report.json"
      reports:
        type: "list"
        required: false
        description: "The list of reports to run"
        default:
          - 'arp_table'
          - 'nics'