---
- name: Semaphore Create Local Credentials
  hosts: all
  gather_facts: no
  vars_files:
    - ../group_vars/all/scm_credentials.yml

  tasks:

    - name: Change the working directory to somedir/ before executing the command
      ansible.builtin.shell: |
            ansible-playbook -i inventory.yml --vault-password-file .vault_pass playbook_latest/create_localuser.yml \
            --limit firewalls \
            -e 'username=neteng' \
            -e 'password={{ neteng-pass }}'
