---
- name: Obtain SCM OAuth2 token
  uri:
    url: "https://auth.apps.paloaltonetworks.com/oauth2/access_token"
    method: POST
    body_format: form-urlencoded
    body:
      client_id: "{{ scm_client_id }}"
      client_secret: "{{ scm_client_secret }}"
      grant_type: "client_credentials"
      scope: "tsg_id:{{ scm_tsg_id }}"
    status_code: 200
    return_content: yes
  register: scm_token_response
  no_log: true

- name: Set token facts
  set_fact:
    scm_access_token: "{{ scm_token_response.json.access_token }}"
  no_log: true

