[panorama]
dicks-pano-panorama01 panorama_host=20.120.21.222 username=panadmin password=llMsswtmrbclh7@K

[firewalls]
dicks-vmseries-lab2-firewall03 panorama_host=40.82.208.208 username=panadmin password=x6d_2ntfshiwfuxH
dicks-vmseries-lab2-firewall04 panorama_host=4.147.169.53 username=panadmin password=x6d_2ntfshiwfuxH

[all:vars]
ansible_connection=local
ansible_python_interpreter=/Users/pmaidana/.pyenv/versions/3.12.5/envs/.venv/bin/python
